source = ~/.config/hypr/colors.conf

group {
    col.border_active = $primary 
    # col.border_inactive = $color10
    
    groupbar {
        enabled = true
        font_family = JetBrainsMono Nerd Font
        font_size = 10
        gradients = true
        height = 15
        priority = 3
        render_titles = true
        scrolling = true
        # text_color = $foreground
        
        col.active = rgba(26,64,171,1)
        col.inactive = rgba(21,46,90,0.8)
        # col.inactive = $background
        # col.locked_active = $color6
        # col.locked_inactive = $color8
    }
}
